package com.aweirdtrashcan.compras.repository

object ComprasOptions {
    val options = arrayOf<String>(
        "Arroz",
        "Feijão",
        "Sabonete",
        "Açúcar",
        "Café",
        "Chá",
        "Leite",
        "Pão",
        "Farinha de trigo",
        "Farinha de rosca",
        "Amido de milho",
        "Goiabada",
        "Chocolate",
        "Bolo",
        "Ração",
        "Areia de Gato",
        "Fermento",
        "Macarrão",
        "Molho de tomate",
        "Leite condensado",
        "Creme de leite",
        "Gelatina",
        "Ketchup",
        "Maionese",
        "Óleo",
        "Azeite",
        "Vinagre",
        "Tempero pronto",
        "Sal",
        "Alface",
        "Repolho",
        "Vagem",
        "Tomate",
        "Pepino",
        "Cebola",
        "Batata",
        "Cenoura",
        "Pimentão",
        "Chuchu",
        "Limão",
        "Banana",
        "Mamão",
        "Melão",
        "Laranja",
        "Abacaxi",
        "Morango",
        "Maçã",
        "Maracujá",
        "Melancia",
        "Bife",
        "Carne Moída",
        "Carne de frango",
        "Peito de frango",
        "Filé Mignon",
        "Presunto",
        "Mussarela",
        "Mortadela",
        "Salsicha",
        "Linguiça",
        "Água mineral",
        "Refrigerante",
        "Suco",
        "Cerveja",
        "Vinho",
        "Detergente",
        "Desinfetante",
        "Água sanitária",
        "Sabão em Pó",
        "Sabão em Pedra",
        "Amaciante",
        "Álcool",
        "Lustra Móveis",
        "Inseticida",
        "Saco de lixo",
        "Papel toalha",
        "Guardanapo",
        "Papel alumínio",
        "Filme plástico",
        "Esponja de aço",
        "Rodo/Vassoura",
        "Fósforo",
        "Vela",
        "Lâmpada",
        "Palito de dente",
        "Filtro para café",
        "Shampoo",
        "Condicionador",
        "Sabonete",
        "Desodorante",
        "Papel higiênico",
        "Creme dental",
        "Fio dental",
        "Escova de dentes",
        "Cotonete",
        "ALgodão",
        "Absorvente"
    )

    val optionsBool = arrayListOf<Boolean>()
}